// Catalogue of realistic Postgres / PostgREST / Supabase errors the incident
// feed (lib/incidentFeed.js) draws from at random. This is flavor data for a
// judge demo, not the connection-saturation incident itself — the pinned
// 53300-on-storefront-api incident lives in lib/data.js and is never drawn
// from here.

export const INCIDENT_CATALOGUE = [
  // ---------------------------------------------------------------- access & RLS
  {
    code: "42501",
    title: "Row-level security blocking prescription inserts",
    resource: "prescriptions",
    severity: "critical",
    symptom: 'new row violates row-level security policy for table "prescriptions"',
    category: "access",
  },
  {
    code: "42501",
    title: "Payments table denies the reporting role",
    resource: "payments",
    severity: "critical",
    symptom: "permission denied for table payments",
    category: "access",
  },
  {
    code: "42501",
    title: "Public schema access denied for analytics role",
    resource: "customers",
    severity: "warning",
    symptom: "permission denied for schema public",
    category: "access",
  },
  {
    code: "PGRST301",
    title: "Session token expired mid-request",
    resource: "storefront-api",
    severity: "warning",
    symptom: "JWT expired",
    category: "access",
  },
  {
    code: "PGRST106",
    title: "PostgREST rejected an unlisted schema",
    resource: "checkout-worker",
    severity: "warning",
    symptom: "the schema must be one of the following: public",
    category: "access",
  },
  {
    code: "28P01",
    title: "Vet-verifier service account rejected",
    resource: "rx-verifier",
    severity: "critical",
    symptom: 'password authentication failed for user "app_rx"',
    category: "access",
  },
  {
    code: null,
    title: "Query returns empty despite matching rows",
    resource: "customers",
    severity: "info",
    symptom: "select returns empty array despite rows existing — RLS policy filtering silently",
    category: "access",
  },

  // ---------------------------------------------------------------- import & ingest
  {
    code: "22021",
    title: "Clinic CSV import rejected on encoding",
    resource: "vet_imports",
    severity: "critical",
    symptom: 'invalid byte sequence for encoding "UTF8": 0x00',
    category: "import",
  },
  {
    code: "22P02",
    title: "Clinic import sent a non-ISO date",
    resource: "vet_imports",
    severity: "warning",
    symptom: 'invalid input syntax for type date: "14/03/2026"',
    category: "import",
  },
  {
    code: "22P02",
    title: "Pet import sent a malformed identifier",
    resource: "pets",
    severity: "warning",
    symptom: 'invalid input syntax for type uuid: "8801"',
    category: "import",
  },
  {
    code: "23503",
    title: "Prescription references a vet that doesn't exist",
    resource: "prescriptions",
    severity: "critical",
    symptom: 'insert or update on table "prescriptions" violates foreign key constraint "prescriptions_vet_id_fkey"',
    category: "import",
  },
  {
    code: "23505",
    title: "Duplicate key on bulk pet import",
    resource: "pets",
    severity: "warning",
    symptom: 'duplicate key value violates unique constraint "pets_pkey"',
    category: "import",
  },
  {
    code: "23502",
    title: "Customer import left a required field blank",
    resource: "customers",
    severity: "warning",
    symptom: 'null value in column "email" violates not-null constraint',
    category: "import",
  },
  {
    code: "22001",
    title: "Ticket subject exceeds column length",
    resource: "support_tickets",
    severity: "warning",
    symptom: "value too long for type character varying(64)",
    category: "import",
  },
  {
    code: "22003",
    title: "Payment amount overflowed its numeric column",
    resource: "payments",
    severity: "warning",
    symptom: "numeric field overflow",
    category: "import",
  },

  // ---------------------------------------------------------------- connections
  {
    code: "53300",
    title: "checkout-worker approaching connection capacity",
    resource: "checkout-worker",
    severity: "critical",
    symptom: "FATAL: remaining connection slots are reserved for non-replication superuser connections",
    category: "connections",
  },
  {
    code: "57P01",
    title: "Connection terminated by administrator command",
    resource: "rx-verifier",
    severity: "warning",
    symptom: "terminating connection due to administrator command",
    category: "connections",
  },
  {
    code: "08006",
    title: "Connection to the primary dropped mid-query",
    resource: "storefront-api",
    severity: "critical",
    symptom: "connection failure — server closed the connection unexpectedly",
    category: "connections",
  },
  {
    code: "53400",
    title: "Configuration limit exceeded on vet-approval pool",
    resource: "rx-verifier",
    severity: "warning",
    symptom: "configuration limit exceeded",
    category: "connections",
  },
  {
    code: "CONNECT_TIMEOUT",
    title: "Edge function timed out waiting on a connection",
    resource: "checkout-worker",
    severity: "warning",
    symptom: "CONNECT_TIMEOUT: connection timed out in serverless function",
    category: "connections",
  },

  // ---------------------------------------------------------------- performance & contention
  {
    code: "57014",
    title: "Refill lookup exceeded the statement timeout",
    resource: "prescriptions",
    severity: "warning",
    symptom: "canceling statement due to statement timeout",
    category: "performance",
  },
  {
    code: "40001",
    title: "Concurrent order updates collided",
    resource: "orders",
    severity: "warning",
    symptom: "could not serialize access due to concurrent update",
    category: "performance",
  },
  {
    code: "40P01",
    title: "Deadlock between shipment status updates",
    resource: "shipments",
    severity: "critical",
    symptom: "deadlock detected",
    category: "performance",
  },
  {
    code: "55P03",
    title: "Inventory row locked by a long-running transaction",
    resource: "inventory",
    severity: "warning",
    symptom: "lock not available",
    category: "performance",
  },
  {
    code: "53200",
    title: "Audit log export ran the server out of memory",
    resource: "audit_logs",
    severity: "critical",
    symptom: "out of memory",
    category: "performance",
  },
  {
    code: null,
    title: "Autovacuum stalled on an inactive replication slot",
    resource: "audit_logs",
    severity: "warning",
    symptom: "autovacuum stalled due to inactive replication slot",
    category: "performance",
  },

  // ---------------------------------------------------------------- schema & PostgREST
  {
    code: "PGRST202",
    title: "RPC call missing from PostgREST's schema cache",
    resource: "inventory",
    severity: "warning",
    symptom: "Could not find the function public.adjust_inventory in the schema cache",
    category: "schema",
  },
  {
    code: "PGRST204",
    title: "New column not yet visible to PostgREST",
    resource: "pets",
    severity: "warning",
    symptom: "Could not find the 'microchip_id' column of 'pets' in the schema cache",
    category: "schema",
  },
  {
    code: "42P01",
    title: "Query against a table that was never created",
    resource: "vet_imports",
    severity: "critical",
    symptom: 'relation "vet_imports_staging" does not exist',
    category: "schema",
  },
  {
    code: "42703",
    title: "Query referenced a renamed column",
    resource: "support_tickets",
    severity: "warning",
    symptom: 'column "priority" does not exist',
    category: "schema",
  },
  {
    code: "42P07",
    title: "Migration collided with an existing table",
    resource: "shipments",
    severity: "warning",
    symptom: 'relation "shipments_v2" already exists',
    category: "schema",
  },
  {
    code: null,
    title: "Schema cache reload needed after a column add",
    resource: "customers",
    severity: "warning",
    symptom: "PostgREST not recognizing new column until schema cache reload",
    category: "schema",
  },

  // ---------------------------------------------------------------- storage & functions
  {
    code: "403",
    title: "Prescription label upload blocked by storage policy",
    resource: "storage.objects",
    severity: "critical",
    symptom: 'new row violates row-level security policy for table "objects"',
    category: "storage",
  },
  {
    code: "546",
    title: "Edge function hit its worker memory limit",
    resource: "checkout-worker",
    severity: "warning",
    symptom: "WORKER_LIMIT exceeded",
    category: "storage",
  },
  {
    code: "504",
    title: "Vet-approval function exceeded its wall clock limit",
    resource: "rx-verifier",
    severity: "warning",
    symptom: "edge function wall clock time limit reached",
    category: "storage",
  },
  {
    code: "503",
    title: "Edge function failed to boot",
    resource: "storefront-api",
    severity: "critical",
    symptom: "BOOT_ERROR: failed to start execution",
    category: "storage",
  },

  // ---------------------------------------------------------------- auth
  {
    code: "500",
    title: "Auth service failed reading the schema",
    resource: "customers",
    severity: "critical",
    symptom: "Database error querying schema",
    category: "auth",
  },
  {
    code: "500",
    title: "New customer signup failed to persist",
    resource: "customers",
    severity: "critical",
    symptom: "Database error saving new user",
    category: "auth",
  },
  {
    code: "403",
    title: "One-time login code expired before use",
    resource: "customers",
    severity: "info",
    symptom: "otp_expired",
    category: "auth",
  },
];
